apiVersion: tenant.aci.upbound.io/v1alpha1
kind: Tenant
metadata:
  annotations:
    meta.upbound.io/example-id: tenant/v1alpha1/tenant
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    annotation: "orchestrator:mso"
    description: from terraform
    nameAlias: tenant

---

